### ISSUE TITLE
cross-site resource warning running nook webapp

### ISSUE THREAD

**Issue by danrubel** [larksystems/nook#121]
When running `webdev serve` and viewing the sign-in page on `localhost`, the sign-in process works, but I see this warning in the JS console...

```
A cookie associated with a cross-site resource at https://google.com/ was set
without the `SameSite` attribute. A future release of Chrome will only deliver cookies
with cross-site requests if they are set with `SameSite=None` and `Secure`.
You can review cookies in developer tools under Application>Storage>Cookies
and see more details at https://www.chromestatus.com/feature/5088147346030592
and https://www.chromestatus.com/feature/5633521622188032.
```

**Comment by marianamarasoiu** [comment]
@danrubel - I can't reproduce this anymore, so I think the problem has disappeared without us needing to do something about it? can you please check if you're still getting the warning? thanks!

**Comment by danrubel** [comment]
@danrubel Yes, it might be inadvertently fixed. I'll start looking for it again.

**Comment by marianamarasoiu** [comment]
Thanks Dan - no rush though.

Interestingly, when I tested this yesterday in one of the production deployments, it seemed to have gone away, but if I serve locally, it still shows up (just did it today).

Searching for the error on stackoverflow, they're saying that the error is triggered by the google servers serving the content rather that our code, so I'm wondering if it's the from cookies that get set via the google login?

**Comment by marianamarasoiu** [comment]
closing as resolved - if the issue re-appears, we can re-open
