### ISSUE TITLE
display # conversation summaries loaded

### ISSUE THREAD

**Issue by danrubel** [larksystems/nook#127]
As per discussion in https://github.com/larksystems/nook/pull/125, display the number of conversations in the DOM (and thus reflected by the scroll bar) vs the total number of conversations in the list.

**Comment by marianamarasoiu** [comment]
Closing as resolved - the lazy list now uses an extra element to approximate the height of the list as if all elements were present, so showing the number of conversation summaries loaded is no longer needed.
