### ISSUE TITLE
Delayed message sending (Measure twice, cut once)

### ISSUE THREAD

**Issue by lukechurch** [larksystems/nook#162]
It's a bit scary to be able to send so many messages so quickly - and with no undo. Esp. from the keyboard shortcuts.

Consider building an 'outbox' facility that buffers the outgoing messages so they can be reviewed before being sent

**Comment by marianamarasoiu** [comment]
Instant message sending is also an issue when replying from a different timezone - sending messages in the middle of the night is not appropriate.

The 'outbox' facility should also include the ability to schedule messages to be sent.
