### ISSUE TITLE
Refactor push_{collection|document}_to_firestore to a helper library

### ISSUE THREAD

**Issue by marianamarasoiu** [larksystems/nook#225]
These are duplicated methods that are being used in multiple data processing scripts.

**Comment by ktkization** [comment]
@marianamarasoiu please assign this to me when you get the time

**Comment by marianamarasoiu** [comment]
Thanks in advance @ktkization!

**Comment by ktkization** [comment]
[PL](https://github.com/larksystems/nook/pull/351) for refactor

**Comment by ktkization** [comment]
@marianamarasoiu  This can now be closed

**Comment by marianamarasoiu** [comment]
thanks @ktkization, closing as fixed
