### ISSUE TITLE
Know which Git SHA is serving

### ISSUE THREAD

**Issue by lukechurch** [larksystems/nook#242]
Because of propagation delays in Firebase, it would help if we could see on the UI which SHA was serving at a given point.

**Comment by lukechurch** [comment]
@marianamarasoiu this might a good thing for Kenneth to help us with?

**Comment by ktkization** [comment]
Here is my PL for this enhancement https://github.com/larksystems/nook/pull/258

**Comment by marianamarasoiu** [comment]
Thanks @ktkization ! I'll assign this issue to me now to propagate the SHA to the UI.

**Comment by ktkization** [comment]
[PL](https://github.com/larksystems/nook/pull/353) for this feature

**Comment by ktkization** [comment]
@marianamarasoiu This can now be closed

**Comment by marianamarasoiu** [comment]
thanks @ktkization, closing as fixed!
