### ISSUE TITLE
Refactor tool scripts to reuse common functionality

### ISSUE THREAD

**Issue by marianamarasoiu** [larksystems/nook#283]
At the moment, there are several things we do in each script that would be great to refactor out into a helper library, for example:
- firebase initialisation
- import and export from firestore
- constants for firebase collections

@ktkization can you start looking into what it would take to tidy up these scripts? thanks!

**Comment by ktkization** [comment]
@marianamarasoiu yes, assing it to me

**Comment by marianamarasoiu** [comment]
I think this is done now - if there's more refactoring to do, we'll add another new issue
