### ISSUE TITLE
psutil doesn't install on ubuntu 18.04

### ISSUE THREAD

**Issue by lukechurch** [larksystems/nook#289]
@ktkization Just tried to pipenv sync on the tools folder - it fails on Ubuntu, with pipenv unable to install psutil

**Comment by ktkization** [comment]
@lukechurch  What error does it fail with?

**Comment by lukechurch** [comment]
Sorry because of the exact way in which I was installing it, that was not
at all easy to get to otherwise would have pasted it here. Maybe try doing
a VM deployment and let me know if you can't repro? I think Alexander might
also be able to help with that?

**Comment by lukechurch** [comment]
https://github.com/commaai/openpilot-tools/issues/34 looks similar

**Comment by ktkization** [comment]
@marianamarasoiu assign this to me please

**Comment by ktkization** [comment]
@lukechurch according to this [#1143](https://github.com/giampaolo/psutil/issues/1143) the `python3.7-dev` package need to be installed in order to compile python extension modules as shown [here](https://github.com/giampaolo/psutil/blob/master/INSTALL.rst)
