### ISSUE TITLE
Read only configuration for Nook

### ISSUE THREAD

**Issue by lukechurch** [larksystems/nook#377]
We'll need a user configuration for Nook that disables all edits and sends - so a 'viewer' mode. We may also need a mode that can edit tags, but not send messages, unclear at the moment.

Needed for a project going live on 21st June

**Comment by lukechurch** [comment]
On reflection I think we don’t need a read only mode, we need something a bit finer grained.

Can send custom messages?
Can send messages?
Show suggested replies column?
Can edit translations?
Can add remove message tags?
Can add remove conversation tags?
Can create new tags? (!)
Can edit notes? (edited)

**Comment by marianamarasoiu** [comment]
closing as resolved
